site_name: Audrey 🔈
site_url: https://audrey.rulerom.com
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
  custom_dir: ../overrides

extra_css:
  - assets/rulerom.css

extra:
  analytics:
    provider: yandex
    property: 107052211

nav:
  - '🏛️ Home': index.md
  - '🔈 Malysh':
    - 'Overview': malysh/index.md
    - 'Amplifiers': malysh/amps.md
    - 'Iron': malysh/iron.md
  - '🧠 Tube Decima': decima.md
  - '📜 License': LICENSE.md
  - '💎 Ecosystem': ecosystem.md
