site_name: Audrey 🔈
site_url: https://audrey.rulerom.com
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
  custom_dir: ../overrides

extra_css:
  - assets/rulerom.css

extra:
  analytics:
    provider: yandex
    property: 107052211

nav:
  - '🏛️ 首页': index.md
  - '🔈 Малыш':
    - '概述': malysh/index.md
    - '放大器': malysh/amps.md
    - '铁件': malysh/iron.md
  - '🧠 电子管 Decima': decima.md
  - '📜 许可证': LICENSE.md
  - '💎 生态系统': ecosystem.md
