site_name: Audrey 🔈
site_url: https://audrey.rulerom.com
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
  custom_dir: ../overrides

extra_css:
  - assets/rulerom.css

extra:
  analytics:
    provider: yandex
    property: 107052211

nav:
  - '🏛️ Главная': index.md
  - '🔈 Малыш':
    - 'Обзор': malysh/index.md
    - 'Усилители': malysh/amps.md
    - 'Железо': malysh/iron.md
  - '🧠 Ламповая Децима': decima.md
  - '💎 Экосистема': ecosystem.md
